"""Detached (asynchronous) run execution.

Launches a subprocess in its own session via ``start_new_session=True`` so it
survives the parent Simulanka process exiting. The run node is committed
immediately with ``status="running"``; finalization is **lazy** — the next call
to ``status`` / ``wait`` / ``reconcile`` reads the ``finished`` marker (written
by the wrapper script) and patches the graph via ``update_attrs``.

Design choices (see memory ``project-async-runner-design`` for the why):

* No background watcher process — the wrapper script writes a marker on its own
  and the host reconciles on demand.
* Graph commands (``graph inspect`` etc.) do **not** auto-reconcile; they show
  the last-committed state. Use ``simulanka run status`` if you want a fresh
  read.
* If the subprocess is SIGKILL'd or the host machine crashes mid-run, the
  ``finished`` marker is absent. Reconcile then probes the pid; if it is dead,
  the run is marked ``failed`` with ``exit_code=None``.
"""

from __future__ import annotations

import contextlib
import hashlib
import os
import shlex
import signal
import subprocess
import time
from dataclasses import dataclass
from datetime import UTC, datetime
from pathlib import Path
from typing import Literal

from ulid import ULID

from simulanka.kernel.apply import apply_patch
from simulanka.kernel.intent import (
    CreateEdgeOp,
    CreateNodeOp,
    CreatePortOp,
    PatchIntent,
    UpdateAttrsOp,
)
from simulanka.layout.project import ProjectLayout
from simulanka.runner.exec import (
    RunnerError,
    _log_file_attrs,
    _maybe_relative,
    _merged_env,
    _nearest_directory,
    _resolve_parent,
)
from simulanka.schema.entities import Node
from simulanka.storage.entity_store import iter_edges, load_node

RunStatus = Literal["running", "done", "failed"]

_EMPTY_SHA256 = "sha256:" + hashlib.sha256(b"").hexdigest()

# Wrapper script template. Quoting strategy:
#   - The run dir is shell-quoted into the template via shlex.quote — it never
#     comes from user input so this is safe.
#   - The user command is written to a separate file `cmd.sh` and executed via
#     `sh cmd.sh`. This avoids embedding arbitrary user content in the wrapper.
_WRAPPER_TEMPLATE = """#!/bin/sh
# Auto-generated by Simulanka. Edits will be lost on rerun.
RUN_DIR={run_dir_quoted}
sh "$RUN_DIR/cmd.sh" > "$RUN_DIR/stdout.log" 2> "$RUN_DIR/stderr.log" < /dev/null
status=$?
date -u +"%Y-%m-%dT%H:%M:%SZ" > "$RUN_DIR/ended_at"
printf "%s\\n" "$status" > "$RUN_DIR/exit_code"
touch "$RUN_DIR/finished"
"""


class RunNotFound(RunnerError):
    """Raised when the target node does not exist or is not a run."""


@dataclass(frozen=True)
class StartResult:
    run_node_id: str
    pid: int
    run_dir: Path
    stdout_path: str
    stderr_path: str


# ---------------------------------------------------------------------------
# start_run
# ---------------------------------------------------------------------------

def start_run(
    layout: ProjectLayout,
    *,
    command: str,
    parent: str,
    name: str,
    workdir: Path | None = None,
    agent: str = "shell",
    env: dict[str, str] | None = None,
    actor: str = "runner:detached",
) -> StartResult:
    """Launch *command* in a detached session and commit the run as ``status=running``."""
    parent_node = _resolve_parent(layout, parent)
    log_parent_node = _nearest_directory(layout, parent_node)

    run_handle = str(ULID())
    run_dir = layout.dot_dir / "runs" / run_handle
    run_dir.mkdir(parents=True, exist_ok=True)

    (run_dir / "cmd.sh").write_text(command + "\n", encoding="utf-8")
    wrapper = run_dir / "run.sh"
    wrapper.write_text(
        _WRAPPER_TEMPLATE.format(run_dir_quoted=shlex.quote(str(run_dir))),
        encoding="utf-8",
    )
    wrapper.chmod(0o755)

    # Touch logs so file nodes can record an initial (empty) content hash.
    stdout_log = run_dir / "stdout.log"
    stderr_log = run_dir / "stderr.log"
    stdout_log.write_bytes(b"")
    stderr_log.write_bytes(b"")

    effective_workdir = (workdir or layout.root).resolve()
    started_at = datetime.now(UTC)

    proc = subprocess.Popen(
        ["sh", str(wrapper)],
        cwd=str(effective_workdir),
        stdin=subprocess.DEVNULL,
        stdout=subprocess.DEVNULL,
        stderr=subprocess.DEVNULL,
        start_new_session=True,
        env=_merged_env(env),
    )
    (run_dir / "pid").write_text(str(proc.pid) + "\n", encoding="utf-8")

    stdout_rel = str(stdout_log.relative_to(layout.root)).replace("\\", "/")
    stderr_rel = str(stderr_log.relative_to(layout.root)).replace("\\", "/")

    run_attrs: dict[str, object] = {
        "command": command,
        "agent": agent,
        "status": "running",
        "exit_code": None,
        "started_at": started_at.isoformat(),
        "ended_at": None,
        "duration_seconds": None,
        "workdir": _maybe_relative(effective_workdir, layout.root),
        "stdout_path": stdout_rel,
        "stderr_path": stderr_rel,
        "run_handle": run_handle,
        "pid": proc.pid,
        "detached": True,
    }

    # Patch 1: run node + 2 log file nodes (with empty-content hashes; they
    # will be refreshed at reconcile time).
    nodes_intent = PatchIntent(
        ops=[
            CreateNodeOp(
                type="run", name=name, parent=parent_node.id, attrs=run_attrs,
            ),
            CreateNodeOp(
                type="file",
                name=f"{name}.stdout.log",
                parent=log_parent_node.id,
                attrs={
                    "fs_path": stdout_rel,
                    "content_hash": _EMPTY_SHA256,
                    "kind": "run_log",
                    "binding": "managed",
                    "size_bytes": 0,
                },
            ),
            CreateNodeOp(
                type="file",
                name=f"{name}.stderr.log",
                parent=log_parent_node.id,
                attrs={
                    "fs_path": stderr_rel,
                    "content_hash": _EMPTY_SHA256,
                    "kind": "run_log",
                    "binding": "managed",
                    "size_bytes": 0,
                },
            ),
        ],
        actor=actor,
        base_graph_version=layout.load_manifest().graph_version,
        note=f"runner: start (detached) {name}",
    )
    receipt = apply_patch(layout, nodes_intent)
    run_node_id, stdout_node_id, stderr_node_id = receipt.nodes

    # Patch 2: produces edges + store log node ids on the run node for fast
    # lookup at reconcile time. Both go in one patch since the run node and
    # file nodes already exist after patch 1.
    edges_intent = PatchIntent(
        ops=[
            CreateEdgeOp(type="produces", source=run_node_id, target=stdout_node_id),
            CreateEdgeOp(type="produces", source=run_node_id, target=stderr_node_id),
            UpdateAttrsOp(
                target=run_node_id,
                attrs={
                    "stdout_node_id": stdout_node_id,
                    "stderr_node_id": stderr_node_id,
                },
            ),
        ],
        actor=actor,
        base_graph_version=layout.load_manifest().graph_version,
        note=f"runner: link {name}",
    )
    apply_patch(layout, edges_intent)

    return StartResult(
        run_node_id=run_node_id,
        pid=proc.pid,
        run_dir=run_dir,
        stdout_path=stdout_rel,
        stderr_path=stderr_rel,
    )


# ---------------------------------------------------------------------------
# reconcile / wait / kill
# ---------------------------------------------------------------------------

def reconcile_run(layout: ProjectLayout, run_node_id: str) -> Node:
    """Read on-disk markers and update the run node if it has finished.

    Idempotent — calling on a run already marked done/failed is a no-op that
    just returns the current node.
    """
    node = _require_run_node(layout, run_node_id)
    if node.attrs.get("status") != "running":
        return node

    run_handle = node.attrs.get("run_handle")
    if not isinstance(run_handle, str):
        raise RunnerError(f"run node {run_node_id} has no run_handle.")
    run_dir = layout.dot_dir / "runs" / run_handle
    finished_marker = run_dir / "finished"
    pid = node.attrs.get("pid")

    if finished_marker.exists():
        exit_code = int((run_dir / "exit_code").read_text(encoding="utf-8").strip())
        ended_at = _parse_iso_z((run_dir / "ended_at").read_text(encoding="utf-8").strip())
        status: RunStatus = "done" if exit_code == 0 else "failed"
    else:
        if isinstance(pid, int) and _is_alive(pid):
            return node  # still running
        # Process disappeared without writing the marker.
        exit_code = None
        ended_at = datetime.now(UTC)
        status = "failed"

    return _finalize(layout, node, status=status, exit_code=exit_code, ended_at=ended_at)


def wait_run(
    layout: ProjectLayout,
    run_node_id: str,
    *,
    timeout: float | None = None,
    poll_interval: float = 0.5,
) -> Node:
    """Block until the run finishes, then return the finalized node.

    Raises ``TimeoutError`` if ``timeout`` elapses without the run finishing.
    """
    deadline = time.monotonic() + timeout if timeout is not None else None
    while True:
        node = reconcile_run(layout, run_node_id)
        if node.attrs.get("status") != "running":
            return node
        if deadline is not None and time.monotonic() >= deadline:
            raise TimeoutError(
                f"wait_run({run_node_id}) timed out after {timeout}s; "
                "subprocess is still running."
            )
        time.sleep(poll_interval)


def kill_run(
    layout: ProjectLayout,
    run_node_id: str,
    *,
    sig: int = signal.SIGTERM,
) -> Node:
    """Signal the run's process group. Subsequent reconcile picks up the death."""
    node = _require_run_node(layout, run_node_id)
    if node.attrs.get("status") != "running":
        return node
    pid = node.attrs.get("pid")
    if not isinstance(pid, int):
        raise RunnerError(f"run {run_node_id} has no pid recorded.")
    with contextlib.suppress(ProcessLookupError):
        os.killpg(pid, sig)
    return node


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def _require_run_node(layout: ProjectLayout, run_node_id: str) -> Node:
    try:
        node = load_node(layout, run_node_id)
    except FileNotFoundError as exc:
        raise RunNotFound(f"no node with id {run_node_id!r}.") from exc
    if node.type != "run":
        raise RunNotFound(f"node {run_node_id!r} is type {node.type!r}, not run.")
    return node


def _is_alive(pid: int) -> bool:
    """Return True iff *pid* refers to a process that is neither gone nor a zombie.

    Zombies show as 'signalable' to ``os.kill(pid, 0)`` but represent already-dead
    processes whose parent hasn't reaped them. We treat them as dead so reconcile
    can transition the run out of ``running``. Falls back to the kill-probe alone
    on non-Linux systems where ``/proc`` isn't available.
    """
    try:
        os.kill(pid, 0)
    except ProcessLookupError:
        return False
    except PermissionError:
        # Exists, we just don't own it.
        return True
    try:
        with open(f"/proc/{pid}/status", encoding="utf-8") as f:
            for line in f:
                if line.startswith("State:"):
                    # e.g., "State:\tZ (zombie)" or "State:\tR (running)"
                    parts = line.split()
                    if len(parts) >= 2 and parts[1] == "Z":
                        return False
                    break
    except FileNotFoundError:
        # /proc not present (or pid disappeared between probes) — assume dead.
        return False
    return True


def _parse_iso_z(s: str) -> datetime:
    return datetime.fromisoformat(s.replace("Z", "+00:00"))


def _finalize(
    layout: ProjectLayout,
    run_node: Node,
    *,
    status: RunStatus,
    exit_code: int | None,
    ended_at: datetime,
) -> Node:
    started_at = _parse_iso_z(str(run_node.attrs["started_at"]))
    duration = (ended_at - started_at).total_seconds()

    stdout_node_id = run_node.attrs.get("stdout_node_id")
    stderr_node_id = run_node.attrs.get("stderr_node_id")
    if not isinstance(stdout_node_id, str) or not isinstance(stderr_node_id, str):
        # Fallback: re-derive from produces edges. Should not happen with
        # start_run as written, but keeps the code robust to manual editing.
        stdout_node_id, stderr_node_id = _derive_log_node_ids(layout, run_node)

    stdout_bytes = (layout.root / str(run_node.attrs["stdout_path"])).read_bytes()
    stderr_bytes = (layout.root / str(run_node.attrs["stderr_path"])).read_bytes()

    ops: list[CreateNodeOp | CreatePortOp | CreateEdgeOp | UpdateAttrsOp] = [
        UpdateAttrsOp(
            target=run_node.id,
            attrs={
                "status": status,
                "exit_code": exit_code,
                "ended_at": ended_at.isoformat(),
                "duration_seconds": duration,
            },
        ),
        UpdateAttrsOp(
            target=stdout_node_id,
            attrs=_log_file_attrs(stdout_bytes, str(run_node.attrs["stdout_path"])),
        ),
        UpdateAttrsOp(
            target=stderr_node_id,
            attrs=_log_file_attrs(stderr_bytes, str(run_node.attrs["stderr_path"])),
        ),
    ]
    apply_patch(
        layout,
        PatchIntent(
            ops=ops,
            actor="runner:reconcile",
            base_graph_version=layout.load_manifest().graph_version,
            note=f"reconcile: {run_node.name} -> {status}",
        ),
    )
    return load_node(layout, run_node.id)


def _derive_log_node_ids(layout: ProjectLayout, run_node: Node) -> tuple[str, str]:
    """Last-resort lookup of stdout/stderr file node ids via produces edges + paths."""
    stdout_rel = str(run_node.attrs["stdout_path"])
    stderr_rel = str(run_node.attrs["stderr_path"])
    stdout_id: str | None = None
    stderr_id: str | None = None
    for edge in iter_edges(layout):
        if edge.type != "produces" or edge.source_id != run_node.id:
            continue
        target = load_node(layout, edge.target_id)
        path = target.attrs.get("fs_path")
        if path == stdout_rel:
            stdout_id = target.id
        elif path == stderr_rel:
            stderr_id = target.id
    if stdout_id is None or stderr_id is None:
        raise RunnerError(
            f"could not locate log nodes for run {run_node.id} via produces edges."
        )
    return stdout_id, stderr_id
